### ISSUE TITLE
hardcoded room-ref in logging?

### ISSUE THREAD

**Issue by marcokemp** [djwlindenaar/LG-thermaV-control#1]
https://github.com/djwlindenaar/LG-thermaV-control/blob/c2ad3fd9fc42d54f50837c5cfddc325fe5e4c66a/LGtherma.yaml#L101

klopt het dat je hier nog logt met jouw hardcoded 19gr room-ref ipv id(huiskamer_thermostaat_target).state ?

**Comment by djwlindenaar** [comment]
Yes it does.... Feel free to fix it and submit a pull request 😉
